[workspace]
# Versioning strategy
versioning = "manual"

# Which crates to exclude from publishing
exclude = ["torii-migration", "examples/*"]

# Publishing order
order = [
    "torii-core",
    "torii-auth-password",
    "torii-auth-oauth",
    "torii-auth-passkey",
    "torii-storage-sqlite",
    "torii-storage-postgres",
    "torii",
]

# Changelog settings
changelog = true
changelog_path = "CHANGELOG.md"
