name: Docs

# TODO: Provide preview of docs on PRs
on:
  push:
    branches:
      - main

jobs:
  docs:
    name: Build documentation
    runs-on: ubuntu-latest
    env:
      MDBOOK_VERSION: v0.4.51 # https://github.com/rust-lang/mdBook/releases
      WRANGLER_VERSION: 4.22.0 # https://www.npmjs.com/package/wrangler
    steps:
      - uses: actions/checkout@v4

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@1.87
        
      - name: Install mdbook
        run: |
          curl -L https://github.com/rust-lang/mdBook/releases/download/${{ env.MDBOOK_VERSION }}/mdbook-${{ env.MDBOOK_VERSION }}-x86_64-unknown-linux-gnu.tar.gz | tar xz
          chmod +x mdbook
          mv mdbook /usr/local/bin/

      - name: Build documentation
        run: cd docs && mdbook build

      - name: Build & Deploy Worker
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          wranglerVersion: ${{ env.WRANGLER_VERSION }}
          workingDirectory: "docs"
